export { BriefPage } from './BriefPage'
export { SectionCard } from './SectionCard'
export { parseMicroserviceBrief, chunkParagraphGroups } from './parser'
export { getBriefForComponent, getAllBriefs } from './briefRegistry'
export type { BriefEntry } from './briefRegistry'
export { HOLDINGS_BRIEF_RAW, EVENT_STORE_BRIEF_RAW, PARTY_BRIEF_RAW, ADAPTER_BRIEF_RAW, VIRTUAL_TABLE_BRIEF_RAW, GENERIC_CONFIGURATION_BRIEF_RAW, CAMT_BRIEF_RAW } from './mockBrief'
export type { MicroserviceBrief, Section, ContentGroup } from './types'
